package wire_test

import (
	"encoding/json"
	"os"
	"reflect"
	"regexp"
	"testing"

	"github.com/xinyao27/jevonian/internal/wire"
	"github.com/xinyao27/jevonian/internal/wire/anthropic"
	"github.com/xinyao27/jevonian/internal/wire/openai"
	"github.com/xinyao27/jevonian/internal/wire/responses"
)

// Differential fixtures generated by running the TypeScript translators in
// src/ (anthropic.ts, responses.ts, wire.ts) over seeded random bodies. Each
// case holds the input and the TS output; Go must produce a deep-equal result.
type fuzzCase struct {
	Fn     string          `json:"fn"`
	Input  json.RawMessage `json:"input"`
	Model  string          `json:"model"`
	Want   json.RawMessage `json:"want"`
	Throws string          `json:"throws"`
}

func normalizeJSON(t *testing.T, v any) any {
	t.Helper()
	raw, err := json.Marshal(v)
	if err != nil {
		t.Fatal(err)
	}
	var out any
	if err := json.Unmarshal(raw, &out); err != nil {
		t.Fatal(err)
	}
	return out
}

// Empty-id fallbacks are random in both builds (call_ + 16 hex); the 24-hex
// form is a deterministic hash and stays compared exactly.
var randomCallID = regexp.MustCompile(`call_[0-9a-f]{16}\b`)

func maskRandom(v any) any {
	raw, _ := json.Marshal(v)
	var out any
	_ = json.Unmarshal(randomCallID.ReplaceAll(raw, []byte("call_RANDOM")), &out)
	return out
}

func TestWireTranslatorsMatchTypeScriptFuzz(t *testing.T) {
	raw, err := os.ReadFile("testdata/ts_wire_fuzz.json")
	if err != nil {
		t.Skip("no TS fuzz fixture")
	}
	var cases []fuzzCase
	if err := json.Unmarshal(raw, &cases); err != nil {
		t.Fatal(err)
	}
	failures := map[string]int{}
	for i, c := range cases {
		var input any
		if err := json.Unmarshal(c.Input, &input); err != nil {
			t.Fatal(err)
		}
		body, _ := input.(map[string]any)
		var got any
		switch c.Fn {
		case "chatToAnthropic":
			got = anthropic.ChatToAnthropic(body)
		case "normalizeAnthropicPrefill":
			got = anthropic.NormalizePrefill(body)
		case "anthropicToChatRequest":
			got = anthropic.ToChatRequest(body, c.Model)
		case "responsesToChatRequest":
			got = responses.ToChatRequest(body, c.Model)
		case "chatToResponses":
			got = responses.ChatToResponses(body, c.Model)
		case "ensureResponsesCallIds":
			got = responses.EnsureCallIDs(body)
		case "normalizeOpenAIMessages":
			msgs, _ := input.([]any)
			got = openai.NormalizeMessages(msgs)
		case "anthropicToolId":
			got = anthropic.ToolID(input)
		default:
			t.Fatalf("unknown fn %s", c.Fn)
		}
		var want any
		if err := json.Unmarshal(c.Want, &want); err != nil {
			t.Fatal(err)
		}
		if !reflect.DeepEqual(maskRandom(normalizeJSON(t, got)), maskRandom(want)) {
			failures[c.Fn]++
			if failures[c.Fn] <= 2 {
				gj, _ := json.Marshal(got)
				wj, _ := json.Marshal(want)
				t.Errorf("case %d %s mismatch\ninput: %s\n  go: %s\n  ts: %s", i, c.Fn, c.Input, gj, wj)
			}
		}
	}
	for fn, n := range failures {
		t.Errorf("%s: %d mismatches", fn, n)
	}
	_ = wire.Body{}
}
