package admin

// Code generated from src/providers.ts PRESETS; DO NOT EDIT by hand without updating the TS source.

// DefaultPresets returns the provider presets the dashboard's "Add provider" form offers
// (GET /api/state -> presets). Each call returns fresh maps so callers may mutate them.
func DefaultPresets() []map[string]any {
	return []map[string]any{
		{"id": "deepseek", "name": "DeepSeek", "type": "both", "baseUrl": "https://api.deepseek.com/v1", "apiKeyEnv": "DEEPSEEK_API_KEY", "hint": "Create an API key on the DeepSeek platform.", "keysUrl": "https://platform.deepseek.com/api_keys"},
		{"id": "anthropic", "name": "Anthropic (Claude)", "type": "anthropic", "baseUrl": "https://api.anthropic.com/v1", "apiKeyEnv": "ANTHROPIC_API_KEY", "hint": "Create an API key in the Anthropic Console.", "keysUrl": "https://console.anthropic.com/settings/keys"},
		{"id": "openai", "name": "OpenAI", "type": "openai", "baseUrl": "https://api.openai.com/v1", "apiKeyEnv": "OPENAI_API_KEY", "hint": "Create an API key on the OpenAI platform.", "keysUrl": "https://platform.openai.com/api-keys"},
		{"id": "moonshotai", "name": "Moonshot (Kimi)", "type": "openai", "baseUrl": "https://api.moonshot.ai/v1", "apiKeyEnv": "MOONSHOT_API_KEY", "hint": "Create an API key in the Moonshot console.", "keysUrl": "https://platform.moonshot.ai/console/api-keys"},
		{"id": "zai", "name": "Z.ai (GLM)", "type": "openai", "baseUrl": "https://api.z.ai/api/paas/v4", "apiKeyEnv": "ZAI_API_KEY", "hint": "Create an API key in the Z.ai console.", "keysUrl": "https://z.ai/manage-apikey/apikey-list"},
		{"id": "minimax", "name": "MiniMax", "type": "openai", "baseUrl": "https://api.minimax.io/v1", "apiKeyEnv": "MINIMAX_API_KEY", "hint": "Create an interface key in the MiniMax user center.", "keysUrl": "https://platform.minimax.io/user-center/basic-information/interface-key"},
		{"id": "qwen", "name": "Alibaba Qwen", "type": "openai", "baseUrl": "https://dashscope-intl.aliyuncs.com/compatible-mode/v1", "apiKeyEnv": "DASHSCOPE_API_KEY", "hint": "Create a DashScope API key in the Alibaba Cloud Model Studio console.", "keysUrl": "https://bailian.console.alibabacloud.com/#/api-key"},
		{"id": "xai", "name": "xAI (Grok)", "type": "openai", "baseUrl": "https://api.x.ai/v1", "apiKeyEnv": "XAI_API_KEY", "hint": "Create an API key in the xAI console.", "keysUrl": "https://console.x.ai/team/default/api-keys"},
		{"id": "google", "name": "Google Gemini", "type": "openai", "baseUrl": "https://generativelanguage.googleapis.com/v1beta/openai", "apiKeyEnv": "GEMINI_API_KEY", "hint": "Create an API key in Google AI Studio.", "keysUrl": "https://aistudio.google.com/apikey"},
		{"id": "openrouter", "name": "OpenRouter", "type": "both", "baseUrl": "https://openrouter.ai/api/v1", "apiKeyEnv": "OPENROUTER_API_KEY", "hint": "Create an API key under OpenRouter → Settings → Keys.", "keysUrl": "https://openrouter.ai/settings/keys"},
		{"id": "orcarouter", "name": "OrcaRouter", "type": "openai", "baseUrl": "https://api.orcarouter.ai/v1", "apiKeyEnv": "ORCAROUTER_API_KEY", "hint": "Create an API key in the OrcaRouter console.", "keysUrl": "https://www.orcarouter.ai/console"},
		{"id": "opencode-go", "name": "OpenCode Go", "type": "both", "baseUrl": "https://opencode.ai/zen/go/v1", "apiKeyEnv": "OPENCODE_GO_API_KEY", "hint": "Sign in at opencode.ai/auth and copy a Go / Zen API key.", "keysUrl": "https://opencode.ai/auth", "billing": "subscription", "syncModels": true},
		{"id": "opencode-zen", "name": "OpenCode Zen", "type": "both", "baseUrl": "https://opencode.ai/zen/v1", "apiKeyEnv": "OPENCODE_API_KEY", "hint": "Sign in at opencode.ai/auth and copy a Zen API key.", "keysUrl": "https://opencode.ai/auth", "billing": "subscription", "syncModels": true},
		{"id": "commandcode", "name": "Command Code", "type": "both", "baseUrl": "https://api.commandcode.ai/provider/v1", "apiKeyEnv": "COMMAND_CODE_API_KEY", "hint": "Sign in on Command Code and create a provider API key.", "keysUrl": "https://commandcode.ai", "billing": "subscription", "syncModels": true},
		{"id": "mistral", "name": "Mistral", "type": "openai", "baseUrl": "https://api.mistral.ai/v1", "apiKeyEnv": "MISTRAL_API_KEY", "hint": "Create an API key in the Mistral console.", "keysUrl": "https://console.mistral.ai/api-keys", "syncModels": true},
		{"id": "groq", "name": "Groq", "type": "openai", "baseUrl": "https://api.groq.com/openai/v1", "apiKeyEnv": "GROQ_API_KEY", "hint": "Create an API key in the Groq console.", "keysUrl": "https://console.groq.com/keys", "syncModels": true},
		{"id": "ollama", "name": "Ollama", "type": "openai", "baseUrl": "http://127.0.0.1:11434/v1", "hint": "Run Ollama locally; no API key required.", "keysUrl": "https://ollama.com", "noKey": true, "syncModels": true},
		{"id": "lmstudio", "name": "LM Studio", "type": "openai", "baseUrl": "http://127.0.0.1:1234/v1", "hint": "Start LM Studio's local server; no API key required.", "keysUrl": "https://lmstudio.ai", "noKey": true, "syncModels": true},
		{"id": "claude-subscription", "name": "Claude (Pro/Max)", "type": "anthropic", "baseUrl": "https://api.anthropic.com/v1", "hint": "Sign in with `claude`; Jevonian reads ~/.claude/.credentials.json.", "keysUrl": "https://code.claude.com/docs/en/oauth", "auth": "oauth", "oauthSource": "claude-code", "billing": "subscription"},
		{"id": "chatgpt-subscription", "name": "ChatGPT (Codex)", "type": "responses", "baseUrl": "https://chatgpt.com/backend-api/codex", "hint": "Sign in with `codex`; Jevonian reads ~/.codex/auth.json.", "keysUrl": "https://github.com/openai/codex#authentication", "auth": "oauth", "oauthSource": "codex", "billing": "subscription"},
		{"id": "antigravity", "name": "Antigravity (Google)", "type": "gemini", "baseUrl": "https://daily-cloudcode-pa.googleapis.com", "hint": "Sign in with the Antigravity IDE or `agy`; reads the local token and project id.", "keysUrl": "https://antigravity.google", "auth": "oauth", "oauthSource": "antigravity", "billing": "subscription"},
		{"id": "devin-subscription", "name": "Devin", "type": "devin", "baseUrl": "https://server.codeium.com", "hint": "Sign in with `devin auth login`; Jevonian reads ~/.local/share/devin/credentials.toml.", "keysUrl": "https://docs.devin.ai/cli", "auth": "oauth", "oauthSource": "devin", "billing": "subscription"},
		{"id": "cursor-subscription", "name": "Cursor", "type": "cursor", "baseUrl": "https://api2.cursor.sh", "hint": "Install Cursor's CLI and sign in with `cursor-agent login`; Jevonian reads its keychain entry or auth.json.", "keysUrl": "https://cursor.com/install", "auth": "oauth", "oauthSource": "cursor", "billing": "subscription"},
		{"id": "workbuddy-ai-subscription", "name": "WorkBuddy AI", "type": "openai", "baseUrl": "https://www.workbuddy.ai/v2", "hint": "Sign in through Jevonian (browser); or use a plaintext WorkBuddy AI desktop session (credential protection off).", "keysUrl": "https://www.workbuddy.ai", "auth": "oauth", "oauthSource": "workbuddy-ai", "billing": "subscription"},
		{"id": "jevonian-remote", "name": "Jevonian (another machine)", "type": "both", "baseUrl": "http://192.168.1.10:8789/v1", "apiKeyEnv": "JEVONIAN_REMOTE_KEY", "hint": "Run Jevonian on the other machine with `--lan`, then use its LAN /v1 URL and a Jevonian API key from that dashboard. The LAN surface is key-protected and never exposes the dashboard.", "keysUrl": "https://github.com/xinyao27/jevonian", "auth": "api-key"},
	}
}
